#!/bin/bash

# http://superuser.com/a/180149
# This will make sure we don't lose our ssh agent forward
# config when re-attaching to a tmux session
if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
