split-window -v -l 20%
split-window -h -l 33%
send-keys "cd ~/code" enter
split-window -v -l 66%
send-keys "cd ~/code" enter
split-window -v -l 50%
send-keys "cd ~/code" enter
select-pane -t 1
send-keys "nvim" enter
rename-window 'app'
